discord:
  token: "YOUR_DISCORD_BOT_TOKEN"
  
app:
  mode: "test" # test / dev / prod

welcome:
  channel_name: # any name

event:
  event_create_channel_name: # any name

time:
  default_tz: "Europe/Paris"