discord:
  token: "YOUR_DISCORD_BOT_TOKEN"
  
app:
  mode: "test" # test / dev / prod

welcome:
  channel_name: # any name
  primary_command: ""
  # secondary_command: ""
  # rules_channel_name: ""      # 可选：有就提示新人先看
  # intro_channel_name: ""      # 可选：自我介绍频道

event:
  event_create_channel_name: # any name

time:
  default_tz: "Europe/Paris"

ads:
  enabled: true # 是否开启
  channel_name: "" # 默认频道
  hour: 9
  minute: 0
  blessing: "祝你今天少踩坑，多出结果。" # 随机祝福语。 TODO：设置成list，或者引入AI

category:
  purge:
    allowed_role_ids: [] # Delete category
    allowed_user_ids: []
